version: '3'
services:
  web:
    build: .
    links:
      - db
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - .:/home/app:cached
    environment:
      RAILS_ENV: 'development'
      PASSENGER_APP_ENV: 'development'
      DB_DATABASE: 'covid_exchange_development'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      DB_PORT: 5432
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  pgdata: {}
  gems: {}
