version: '3.4'
services:
  web:
    build: 
      context: .
      target: covidledger_base
    links:
      - db
    ports:
      - "3000:3000"
      - "8080:80"
    volumes:
      - .:/home/app:cached
    environment:
      RAILS_ENV: 'development'
      PASSENGER_APP_ENV: 'development'
      DB_DATABASE: 'covid_exchange_development'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      DB_PORT: 5432
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  pgdata: 
  gems: 
